# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'kalkulator_wyborczy.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1176, 858)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(600, 290, 71, 21))
        self.label_3.setPixmap(QPixmap(u"images/Logo_Koalicja_Obywatelska_2023.svg.png"))
        self.label_3.setScaledContents(True)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(690, 290, 51, 21))
        self.label_5.setPixmap(QPixmap(u"images/Lewica_01.svg.png"))
        self.label_5.setScaledContents(True)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(860, 280, 61, 31))
        self.label_7.setPixmap(QPixmap(u"images/Konfederacja_03.svg.png"))
        self.label_7.setScaledContents(True)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(770, 290, 67, 17))
        self.label_9.setPixmap(QPixmap(u"images/Trzecia_Droga_logo.png"))
        self.label_9.setScaledContents(True)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(530, 280, 41, 41))
        self.label.setPixmap(QPixmap(u"images/Logo_PiS_Jasne.png"))
        self.label.setScaledContents(True)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(40, 10, 271, 31))
        font = QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(130, 300, 89, 25))
        self.graphicsView = QGraphicsView(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        self.graphicsView.setGeometry(QRect(390, 50, 731, 221))
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(560, 0, 371, 41))
        font1 = QFont()
        font1.setPointSize(16)
        self.label_13.setFont(font1)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.centralwidget)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(960, 280, 41, 31))
        self.label_14.setPixmap(QPixmap(u"images/Mniejszo\u015b\u0107_Niemiecka.svg.png"))
        self.label_14.setScaledContents(True)
        self.label_15 = QLabel(self.centralwidget)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(540, 360, 131, 17))
        self.label_PiSKonf = QLabel(self.centralwidget)
        self.label_PiSKonf.setObjectName(u"label_PiSKonf")
        self.label_PiSKonf.setGeometry(QRect(690, 360, 67, 17))
        self.label_16 = QLabel(self.centralwidget)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(880, 360, 71, 17))
        self.label_Opposition = QLabel(self.centralwidget)
        self.label_Opposition.setObjectName(u"label_Opposition")
        self.label_Opposition.setGeometry(QRect(960, 360, 67, 17))
        self.label_PiS = QLabel(self.centralwidget)
        self.label_PiS.setObjectName(u"label_PiS")
        self.label_PiS.setGeometry(QRect(520, 320, 67, 17))
        self.label_PiS.setAlignment(Qt.AlignCenter)
        self.label_KO = QLabel(self.centralwidget)
        self.label_KO.setObjectName(u"label_KO")
        self.label_KO.setGeometry(QRect(600, 320, 67, 17))
        self.label_KO.setAlignment(Qt.AlignCenter)
        self.label_Lewica = QLabel(self.centralwidget)
        self.label_Lewica.setObjectName(u"label_Lewica")
        self.label_Lewica.setGeometry(QRect(680, 320, 67, 17))
        self.label_Lewica.setAlignment(Qt.AlignCenter)
        self.label_TD = QLabel(self.centralwidget)
        self.label_TD.setObjectName(u"label_TD")
        self.label_TD.setGeometry(QRect(770, 320, 67, 17))
        self.label_TD.setAlignment(Qt.AlignCenter)
        self.label_Konfederacja = QLabel(self.centralwidget)
        self.label_Konfederacja.setObjectName(u"label_Konfederacja")
        self.label_Konfederacja.setGeometry(QRect(860, 320, 67, 17))
        self.label_Konfederacja.setAlignment(Qt.AlignCenter)
        self.label_MN = QLabel(self.centralwidget)
        self.label_MN.setObjectName(u"label_MN")
        self.label_MN.setGeometry(QRect(950, 320, 67, 17))
        self.label_MN.setAlignment(Qt.AlignCenter)
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(40, 220, 271, 27))
        self.horizontalLayout_5 = QHBoxLayout(self.widget)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.label_8 = QLabel(self.widget)
        self.label_8.setObjectName(u"label_8")

        self.horizontalLayout_5.addWidget(self.label_8)

        self.lineEdit_Konfederacja = QLineEdit(self.widget)
        self.lineEdit_Konfederacja.setObjectName(u"lineEdit_Konfederacja")

        self.horizontalLayout_5.addWidget(self.lineEdit_Konfederacja)

        self.widget1 = QWidget(self.centralwidget)
        self.widget1.setObjectName(u"widget1")
        self.widget1.setGeometry(QRect(40, 260, 271, 21))
        self.horizontalLayout_6 = QHBoxLayout(self.widget1)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_11 = QLabel(self.widget1)
        self.label_11.setObjectName(u"label_11")

        self.horizontalLayout_6.addWidget(self.label_11)

        self.textBrowser = QTextBrowser(self.widget1)
        self.textBrowser.setObjectName(u"textBrowser")

        self.horizontalLayout_6.addWidget(self.textBrowser)

        self.widget2 = QWidget(self.centralwidget)
        self.widget2.setObjectName(u"widget2")
        self.widget2.setGeometry(QRect(41, 60, 271, 27))
        self.horizontalLayout = QHBoxLayout(self.widget2)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.widget2)
        self.label_2.setObjectName(u"label_2")
        font2 = QFont()
        font2.setPointSize(11)
        self.label_2.setFont(font2)
        self.label_2.setTextFormat(Qt.AutoText)

        self.horizontalLayout.addWidget(self.label_2)

        self.lineEdit_PiS = QLineEdit(self.widget2)
        self.lineEdit_PiS.setObjectName(u"lineEdit_PiS")

        self.horizontalLayout.addWidget(self.lineEdit_PiS)

        self.widget3 = QWidget(self.centralwidget)
        self.widget3.setObjectName(u"widget3")
        self.widget3.setGeometry(QRect(40, 140, 271, 27))
        self.horizontalLayout_3 = QHBoxLayout(self.widget3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.widget3)
        self.label_6.setObjectName(u"label_6")

        self.horizontalLayout_3.addWidget(self.label_6)

        self.lineEdit_Lewica = QLineEdit(self.widget3)
        self.lineEdit_Lewica.setObjectName(u"lineEdit_Lewica")

        self.horizontalLayout_3.addWidget(self.lineEdit_Lewica)

        self.widget4 = QWidget(self.centralwidget)
        self.widget4.setObjectName(u"widget4")
        self.widget4.setGeometry(QRect(40, 100, 271, 27))
        self.horizontalLayout_2 = QHBoxLayout(self.widget4)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_4 = QLabel(self.widget4)
        self.label_4.setObjectName(u"label_4")

        self.horizontalLayout_2.addWidget(self.label_4)

        self.lineEdit_KO = QLineEdit(self.widget4)
        self.lineEdit_KO.setObjectName(u"lineEdit_KO")

        self.horizontalLayout_2.addWidget(self.lineEdit_KO)

        self.widget5 = QWidget(self.centralwidget)
        self.widget5.setObjectName(u"widget5")
        self.widget5.setGeometry(QRect(41, 181, 271, 27))
        self.horizontalLayout_4 = QHBoxLayout(self.widget5)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_10 = QLabel(self.widget5)
        self.label_10.setObjectName(u"label_10")

        self.horizontalLayout_4.addWidget(self.label_10)

        self.lineEdit_TD = QLineEdit(self.widget5)
        self.lineEdit_TD.setObjectName(u"lineEdit_TD")

        self.horizontalLayout_4.addWidget(self.lineEdit_TD)

        self.label_error = QLabel(self.centralwidget)
        self.label_error.setObjectName(u"label_error")
        self.label_error.setGeometry(QRect(40, 340, 271, 20))
        self.label_error.setAlignment(Qt.AlignCenter)
        self.line = QFrame(self.centralwidget)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(0, 390, 1181, 20))
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_19 = QLabel(self.centralwidget)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(26, 420, 291, 31))
        self.label_19.setFont(font)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.stackedWidget = QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(330, 410, 821, 381))
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.verticalLayout = QVBoxLayout(self.page)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.label_17 = QLabel(self.page)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setAlignment(Qt.AlignCenter)

        self.verticalLayout.addWidget(self.label_17)

        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.tableWidget_results = QTableWidget(self.page_2)
        self.tableWidget_results.setObjectName(u"tableWidget_results")
        self.tableWidget_results.setGeometry(QRect(325, 60, 491, 231))
        self.widget6 = QWidget(self.page_2)
        self.widget6.setObjectName(u"widget6")
        self.widget6.setGeometry(QRect(20, 20, 291, 371))
        self.verticalLayout_2 = QVBoxLayout(self.widget6)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.tabWidget = QTabWidget(self.widget6)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.label_map = QLabel(self.tab)
        self.label_map.setObjectName(u"label_map")
        self.label_map.setGeometry(QRect(0, 30, 281, 251))
        self.label_map.setScaledContents(True)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_18 = QLabel(self.tab_2)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 20, 91, 17))
        self.label_population = QLabel(self.tab_2)
        self.label_population.setObjectName(u"label_population")
        self.label_population.setGeometry(QRect(150, 20, 101, 17))
        self.label_20 = QLabel(self.tab_2)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(20, 70, 101, 17))
        self.label_area = QLabel(self.tab_2)
        self.label_area.setObjectName(u"label_area")
        self.label_area.setGeometry(QRect(150, 70, 101, 17))
        self.label_21 = QLabel(self.tab_2)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(20, 120, 141, 17))
        self.label_density = QLabel(self.tab_2)
        self.label_density.setObjectName(u"label_density")
        self.label_density.setGeometry(QRect(150, 120, 101, 17))
        self.label_24 = QLabel(self.tab_2)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 180, 241, 17))
        self.label_popmandate = QLabel(self.tab_2)
        self.label_popmandate.setObjectName(u"label_popmandate")
        self.label_popmandate.setGeometry(QRect(100, 210, 67, 17))
        self.label_popmandate.setAlignment(Qt.AlignCenter)
        self.label_26 = QLabel(self.tab_2)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 250, 251, 20))
        self.label_voters_per_seat = QLabel(self.tab_2)
        self.label_voters_per_seat.setObjectName(u"label_voters_per_mandate")
        self.label_voters_per_seat.setGeometry(QRect(100, 280, 67, 17))
        self.label_voters_per_seat.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_2, "")

        self.verticalLayout_2.addWidget(self.tabWidget)

        self.label_22 = QLabel(self.page_2)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(450, 310, 131, 17))
        self.label_mandates = QLabel(self.page_2)
        self.label_mandates.setObjectName(u"label_mandates")
        self.label_mandates.setGeometry(QRect(620, 310, 67, 17))
        self.label_attendance = QLabel(self.page_2)
        self.label_attendance.setObjectName(u"label_attendance")
        self.label_attendance.setGeometry(QRect(620, 350, 67, 17))
        self.label_23 = QLabel(self.page_2)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(450, 350, 141, 17))
        self.label_district = QLabel(self.page_2)
        self.label_district.setObjectName(u"label_district")
        self.label_district.setGeometry(QRect(330, 10, 481, 31))
        self.label_district.setFont(font1)
        self.label_district.setAlignment(Qt.AlignCenter)
        self.stackedWidget.addWidget(self.page_2)
        self.districts = QListWidget(self.centralwidget)
        self.districts.setObjectName(u"districts")
        self.districts.setGeometry(QRect(25, 460, 291, 341))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1176, 22))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.stackedWidget.setCurrentIndex(1)
        self.tabWidget.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Kalkulator wyborczy", None))
        self.label_3.setText("")
        self.label_5.setText("")
        self.label_7.setText("")
        self.label_9.setText("")
        self.label.setText("")
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Wpisz wyniki wybor\u00f3w</span></p></body></html>", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Oblicz", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Podzia\u0142 mandat\u00f3w</span></p></body></html>", None))
        self.label_14.setText("")
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"PiS + Konfederacja:", None))
        self.label_PiSKonf.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"Opozycja:", None))
        self.label_Opposition.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_PiS.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p>0</p></body></html>", None))
        self.label_KO.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_Lewica.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_TD.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_Konfederacja.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_MN.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600;\">Konfederacja</span></p></body></html>", None))
        self.lineEdit_Konfederacja.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Inne", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#1a5fb4;\">Prawo i Sprawiedliwo\u015b\u0107</span></p></body></html>", None))
        self.lineEdit_PiS.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#ed333b;\">Nowa Lewica                 </span></p></body></html>", None))
        self.lineEdit_Lewica.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#ff7800;\">Koalicja Obywatelska    </span></p></body></html>", None))
        self.lineEdit_KO.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" font-weight:600; color:#33d17a;\">Trzecia Droga</span></p></body></html>", None))
        self.lineEdit_TD.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_error.setText("")
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" text-decoration: underline;\">Wybierz okr\u0119g wyborczy</span></p></body></html>", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p><span style=\" color:#77767b;\">Wpisz wynik wybor\u00f3w i wybierz okr\u0119g</span></p></body></html>", None))
        self.label_map.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Mapa okr\u0119gu", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Populacja:", None))
        self.label_population.setText("")
        self.label_20.setText(QCoreApplication.translate("MainWindow", u"Powierzchnia:", None))
        self.label_area.setText("")
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"G\u0119sto\u015b\u0107: ", None))
        self.label_density.setText("")
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"Liczba mieszka\u0144c\u00f3w na mandat:", None))
        self.label_popmandate.setText("")
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"Względna (do Warszawy) siła głosu:", None))
        self.label_voters_per_seat.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Informacje o okr\u0119gu", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Liczba mandat\u00f3w:", None))
        self.label_mandates.setText("")
        self.label_attendance.setText("")
        self.label_23.setText(QCoreApplication.translate("MainWindow", u"Frekwencja w 2019:", None))
        self.label_district.setText("")
    # retranslateUi

